# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: csv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcsv.proto\"\x1e\n\nCSVRequest\x12\x10\n\x08\x63sv_data\x18\x01 \x01(\t\"\x1b\n\x0b\x43SVResponse\x12\x0c\n\x04rows\x18\x01 \x03(\t24\n\nCSVService\x12&\n\x07SendCSV\x12\x0b.CSVRequest\x1a\x0c.CSVResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'csv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CSVREQUEST._serialized_start=13
  _CSVREQUEST._serialized_end=43
  _CSVRESPONSE._serialized_start=45
  _CSVRESPONSE._serialized_end=72
  _CSVSERVICE._serialized_start=74
  _CSVSERVICE._serialized_end=126
# @@protoc_insertion_point(module_scope)
