# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import csv_pb2 as csv__pb2


class CSVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendCSV = channel.unary_unary(
                '/CSVService/SendCSV',
                request_serializer=csv__pb2.CSVRequest.SerializeToString,
                response_deserializer=csv__pb2.CSVResponse.FromString,
                )


class CSVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CSVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.SendCSV,
                    request_deserializer=csv__pb2.CSVRequest.FromString,
                    response_serializer=csv__pb2.CSVResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CSVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CSVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CSVService/SendCSV',
            csv__pb2.CSVRequest.SerializeToString,
            csv__pb2.CSVResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
